### ISSUE TITLE
Make BlueM.Datasets repository public?

### ISSUE THREAD

**Issue by TobiasRosskopf** [bluemodel/BlueM.Datasets#1]
In [https://bluemodel.github.io/BlueM.Wave/articles/intro.html](https://bluemodel.github.io/BlueM.Wave/articles/intro.html) we refer to [BlueM.Datasets repository](https://github.com/bluemodel/BlueM.Datasets) to be able to run all tests of BlueM.Wave. But this repository is still private and outside users who want to collaborate to public BlueM.Wave can not clone the test data. So is there any intention to make this repository also public or is this only possible when BlueM.Sim will be public?

**Comment by jamaa** [comment]
Yes we definitely should make it public. Better to anonymize some of the data in there beforehand though. I will take care of it.

**Comment by jamaa** [comment]
Done

**Comment by TobiasRosskopf** [comment]
Wow, that was fast! 😮👍🏻

**Comment by jamaa** [comment]
well, it's been on the back of my mind for a long time and I just needed the nudge to actually do it ;-)
